
# main.http
@host=http://127.0.0.1:5000
GET {{host}}/

# About
###
GET {{host}}/about

###
GET {{host}}/profile/101

### 
GET {{host}}/profile/102


###
POST {{host}}/post/add?q1=




































