# main.http

@host=http://127.0.0.1:5000
GET {{host}}/

# About
###
GET {{host}}/about

###
GET {{host}}/profile/101

### 
GET {{host}}/profile/102

###
POST {{host}}/post/add?q1=v1&q2=v2
Content-Type: application/json

{
    "_id": 101,
    "author": "Mike",
    "text": "My first blog post!",
    "random_number": 33,
    "tags": ["mongodb", "Python", "pymongo"]
}

###

POST {{host}}/contact/save

Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "message": "I would like to learn more about MongoDB!"
}



































